apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-arch
  namespace: default
  labels:
    app: mirror-arch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
