apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-parrot
  namespace: default
  labels:
    app: mirror-parrot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Gi
