kind: ConfigMap
apiVersion: v1
metadata:
  name: caddy-config-mirror
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>0xEmma's Mirrors</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body>
        <div class="flex h-screen w-full items-center justify-center bg-[#1e1e1e] font-mono text-[#c6c6c6]">
            <div class="border border-[#4CAF50] p-12 rounded-lg">
                <header class="bg-[#2d2d2d] px-4 py-2">
                    <h1 class="text-lg font-bold text-[#4CAF50]">0xEmma's Mirrors</h1>
                </header>
                <main class="flex-1 overflow-auto px-4 py-6">
                    <ul class="space-y-2">
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/almalinux/">
                                AlmaLinux
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/arch/">
                                Arch
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/blackarch/">
                                BlackArch
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/epel/">
                                Fedora EPEL
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/kali-images/">
                                Kali ISOs
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/kali/">
                                Kali
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/parrot/">
                                Parrot
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/ubuntu-releases/">
                                Ubuntu ISOs
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/ubuntu/">
                                Ubuntu
                            </a>
                        </li>
                        <li>
                            <span class="text-[#9cdcfe]">$</span>
                            <a class="text-[#4CAF50] hover:underline" href="/voidlinux/">
                                Voidlinux
                            </a>
                        </li>
                    </ul>
                </main>
            </div>
        </div>
    </body>
    </html>
  robots.txt: |
    user-agent: *
    Allow: /$
    Disallow: /

    User-agent: ClaudeBot
    Disallow: /
