apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror
  namespace: default
  labels:
    app: mirror
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mirror
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mirror
    spec:
      containers:
        - name: mirror
          image: 0xemma/nginx-autoindex:json-2
          resources:
            limits:
              memory: 8000Mi
            requests:
              cpu: 100m
              memory: 8000Mi
          volumeMounts:
            - name: config
              mountPath: /var/lib/nginx/html
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: caddy-config-mirror
