apiVersion: batch/v1
kind: CronJob
metadata:
  name: mirrorupdate-arch
  namespace: default
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mirrorupdate-ubuntu
              imagePullPolicy: Always
              image: ghcr.io/0xemma/mirror-updater:v2.0.0
              env:
                - name: TARGET
                  value: /ext/mirror/arch
                - name: SOURCE
                  value: rsync://arch.mirror.constant.com/archlinux/
                - name: LASTUPDATE
                  value: https://arch.mirror.constant.com/archlinux/lastupdate
                - name: FIRST
                  value: "not"
              volumeMounts:
                - name: mirror-pvc
                  mountPath: /ext/mirror/
          restartPolicy: OnFailure
          volumes:
            - name: mirror-pvc
              persistentVolumeClaim:
                claimName: mirror-arch
