apiVersion: batch/v1
kind: CronJob
metadata:
  name: mirrorupdate-parrot
  namespace: default
spec:
  schedule: "30 */5 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mirrorupdate-parrot
              imagePullPolicy: Always
              image: ghcr.io/0xemma/mirror-updater:v0.0.4
              command:
                - /scripts/parrot-clone.sh
              volumeMounts:
                - name: mirror-pvc
                  mountPath: /ext/mirror
          restartPolicy: OnFailure
          volumes:
            - name: mirror-pvc
              persistentVolumeClaim:
                claimName: mirror-parrot
