apiVersion: v1
kind: Service
metadata:
  name: mirror-rsync
  namespace: default
spec:
  selector:
    app: mirror-rsync
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: mirror-rsync
    protocol: TCP
    port: 873