apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-rockylinux
  namespace: default
  labels:
    app: mirror-rockylinux
spec:
  storageClassName: csi-fs-hdd-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
