apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-ubuntu-iso
  namespace: default
  labels:
    app: mirror-ubuntureleases
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
