apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-blackarch
  namespace: default
  labels:
    app: mirror-blackarch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
