apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-kali-images
  namespace: default
  labels:
    app: mirror-kali-images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
